### ISSUE TITLE
logout asks for user to login to complete action

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-client#237]
This is taken from a user on the anaconda mailing list.  He's seeing some pretty weird behavior.

```bash
(root)$ anaconda --version
anaconda Command line client (version 1.1.2)

(root)$ anaconda login
Using anaconda-server api site https://api.anaconda.org
Username: drf5n
drf5n's Password: 
[WARNING] It appears you are already logged in from host v21837.local
[WARNING] Logging in again will remove the previous token.  (This could cause troubles with virtual machines with the same hostname)
[WARNING] Otherwise you can login again and specify a different hostname with "--hostname"
Would you like to continue [Y|n]: y
drf5n's login successful

(root)$ anaconda whoami
Using anaconda-server api site https://api.anaconda.org
Anonymous User

(root)$ anaconda logout
Using anaconda-server api site https://api.anaconda.org
The action you are performing requires authentication, please sign in:
Using anaconda-server api site https://api.anaconda.org
Username: drf5n
drf5n's Password: 
[WARNING] It appears you are already logged in from host v21837.local
[WARNING] Logging in again will remove the previous token.  (This could cause troubles with virtual machines with the same hostname)
[WARNING] Otherwise you can login again and specify a different hostname with "--hostname"
Would you like to continue [Y|n]: y
drf5n's login successful
Using anaconda-server api site https://api.anaconda.org
[Unauthorized] (u'This domain requires token authentication', 401)
```

**Comment by PeterDSteinberg** [comment]
I'm having trouble reproducing this.  I see that logout.py ends up making a DELETE request to``` <domain>/authentications```.  In the [AS repo here](https://github.com/Anaconda-Server/anaconda-server/blob/develop/binstar/sites/api/views/authentications.py#L142) the /authentications uri is shown with the ```@requires_auth_token('api:read')``` decorator.  Is it possible @srossross  that hitting that URL is what is triggering the necessity to log in during logout.  However if that request were unsuccessful, then we would expect an error class to be raised [here](https://github.com/Anaconda-Server/anaconda-client/blob/develop/binstar_client/__init__.py#L142).  I don't see a recent change in AS with respect to this decorator.

**Comment by srossross** [comment]
@PeterDSteinberg to reproduce, can you try to log in and then remove the token from the gui `/settings/access` -> details -> Revoke Token.

Then try running the `anaconda logout` command.

**Comment by ijstokes** [comment]
This is all on the Anaconda mailing list and I'm sure the OP would appreciate some suggestions from someone who understands what might be going on here better than I do.  Here is the outcome of a suggestion I made to manually (using `rm`) remove the tokens, update conda, and then try again:

```bash
(root)$ ls -Flad ~/Library/Application\ Support/binstar/*.token 
-rw-------  1 drf  staff  39 Nov 11 01:41 /Users/drf/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token

(root)$ rm ~/Library/Application\ Support/binstar/*.token 

(root)$ ls -Flad ~/Library/Application\ Support/binstar/*.token 
ls: /Users/drf/Library/Application Support/binstar/*.token: No such file or directory
```

The first bits work:

```bash
(root)$  source activate root
discarding /Users/drf/anaconda/bin from PATH
prepending /Users/drf/anaconda/bin to PATH

(root)$  conda install -f conda=3.14 anaconda-client conda-env
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/drf/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.14.1               |           py27_0         169 KB

The following packages will be UPDATED:

    anaconda-client: 1.1.2-py27_0  --> 1.1.2-py27_0 
    conda:           3.14.0-py27_0 --> 3.14.1-py27_0
    conda-env:       2.4.4-py27_0  --> 2.4.4-py27_0 

Proceed ([y]/n)? y

Fetching packages ...
conda-3.14.1-p 100% |########################################################################| Time: 0:00:00   2.53 MB/s
[      COMPLETE      ]|###########################################################################################| 100%
Extracting packages ...
[      COMPLETE      ]|###########################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###########################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###########################################################################################| 100%
(root)$  
```

but then the same error:

```bash
(root)$  conda create -n test_r -c r r-essentials

Fetching package metadata: ....
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)
Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)

^C

Traceback (most recent call last):
  File "/Users/drf/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    offline=args.offline)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 549, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 140, in fetch_repodata
    use_cache=use_cache, session=session)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 100, in fetch_repodata
    verify=config.ssl_verify)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 375, in prepare_request
    auth = get_netrc_auth(request.url)
  File "/Users/drf/anaconda/lib/python2.7/site-packages/requests/utils.py", line 101, in get_netrc_auth
    _netrc = netrc(netrc_path).authenticators(host)
  File "/Users/drf/anaconda/lib/python2.7/netrc.py", line 35, in __init__
    self._parse(file, fp, default_netrc)
  File "/Users/drf/anaconda/lib/python2.7/netrc.py", line 90, in _parse
    login = lexer.get_token()
  File "/Users/drf/anaconda/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/Users/drf/anaconda/lib/python2.7/shlex.py", line 137, in read_token
    elif nextchar in self.whitespace:
KeyboardInterrupt
```

**Comment by drf5n** [comment]
Yep.  That's me.  I've gotten to this point from earlier issues noted in https://github.com/Anaconda-Server/docs.anaconda.org/issues/145

**Comment by drf5n** [comment]
Also, if I try a python 3 environment, I get this:

    (root)$ . activate python3
    discarding /Users/drf/anaconda/bin from PATH
    prepending /Users/drf/anaconda/envs/python3/bin to PATH
    (python3)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    Member since: Sat Jun 13 10:01:53 2015
      +user_type: user
    (python3)$ anaconda logout
    Using anaconda-server api site https://api.anaconda.org
    logout successful
    (python3)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (python3)$ anaconda login
    Using anaconda-server api site https://api.anaconda.org
    [ERROR] 
    Traceback (most recent call last):
      File "/Users/drf/anaconda/envs/python3/bin/anaconda", line 6, in <module>
        sys.exit(main())
      File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 82, in main
        description=__doc__, version=version)
      File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
        return args.main(args)
      File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/binstar_client/commands/login.py", line 101, in main
        interactive_login(args)
      File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/binstar_client/commands/login.py", line 96, in interactive_login
        token = interactive_get_token(args)
      File "/Users/drf/anaconda/envs/python3/lib/python3.5/site-packages/binstar_client/commands/login.py", line 38, in interactive_get_token
        username = input('Username: ')
    AttributeError: 'ColorStream' object has no attribute 'errors'
    (python3)$ anaconda --version
    anaconda Command line client (version 1.1.2)
    (python3)$ conda --version
    conda 3.14.1
    (python3)$ python --version
    Python 3.5.0 :: Continuum Analytics, Inc.
    (python3)$

Switching to 2.7 and logging in again:

    (python3)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (python3)$ . activate py27
    discarding /Users/drf/anaconda/envs/python3/bin from PATH
    prepending /Users/drf/anaconda/envs/py27/bin to PATH
    (py27)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (py27)$ anaconda login
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    login successful
    (py27)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (py27)$ anaconda logout
    Using anaconda-server api site https://api.anaconda.org
    The action you are performing requires authentication, please sign in:
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    [WARNING] It appears you are already logged in from host v21837.vims.edu
    [WARNING] Logging in again will remove the previous token.  (This could cause troubles with virtual machines with the same hostname)
    [WARNING] Otherwise you can login again and specify a different hostname with "--hostname"
    Would you like to continue [Y|n]: y
    drf5n's login successful
    Using anaconda-server api site https://api.anaconda.org
    [Unauthorized] (u'This domain requires token authentication', 401)
    (py27)$

**Comment by PeterDSteinberg** [comment]
@srossross: When trying the scenario you suggested (log in, then revoke the token via UI settings/access -> details -> revoke, then anaconda logout), I am seeing that the DELETE request to /api/authentications is a 401 status code.  I'll put some logging in there to see more.

**Comment by PeterDSteinberg** [comment]
The source of the 401 status code is either [this line in the requires_auth_token decorator](https://github.com/Anaconda-Server/anaconda-server/blob/develop/binstar/sites/api/decorators.py#L45) or [this line in the requires_auth_token decorator](https://github.com/Anaconda-Server/anaconda-server/blob/develop/binstar/sites/api/decorators.py#L53)

**Comment by PeterDSteinberg** [comment]
When anaconda-client gets the 401 response back, it raises errors.Unauthorized [here](https://github.com/Anaconda-Server/anaconda-client/blob/develop/binstar_client/__init__.py#L153) and that exception is caught [here in cli.py](https://github.com/Anaconda-Server/anaconda-client/blob/develop/binstar_client/scripts/cli.py#L66) where cli.py then forces logging in again because of the Unauthorized error.

**Comment by drf5n** [comment]
Prior to the login-to-logout oddity, it appears that the login might have been unsuccessful somehow:

    (py27)$ rm ~/Library/Application\ Support/binstar/*.token 
    (py27)$ rm ~/Library/Application\ Support/binstar/*.token 
    rm: /Users/drf/Library/Application Support/binstar/*.token: No such file or directory
    (py27)$ anaconda login
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    login successful
    (py27)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (py27)$ anaconda -v whoami
    [DEBUG] Found login token: /Users/drf/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
    [DEBUG] (u'This domain requires token authentication', 401)
    Anonymous User
    (py27)$ cat |sed 's/^/    /' > /tmp/junk
    (py27)$ anaconda login
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    login successful
    (py27)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (py27)$ anaconda -v whoami
    [DEBUG] Found login token: /Users/drf/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
    [DEBUG] (u'This domain requires token authentication', 401)
    Anonymous User
    (py27)$ 


Shouldn't the 'anaconda whoami' return 'drf5n' rather than 'Anonymous User'?  Is this a different issue?

Concurrent with the 'rm ~/Library/Application\ Support/binstar/*.token' line, I logged into https://anaconda.org/settings/access and clicked a Details/Revoke Token for each of the existing tokens until they were both gone.

**Comment by electronwill** [comment]
Does the 'anaconda login --username jsmith' workaround work for you?

**Comment by drf5n** [comment]
The workaround works in the python3 environment, and it appears that the login is persistent across environment changes:

    (python3)$ anaconda -v login --username drf5n --password $JUNK
    login successful
    drf5n's (python3)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    Member since: Sat Jun 13 10:01:53 2015
      +user_type: user
    (python3)$ anaconda logout
    Using anaconda-server api site https://api.anaconda.org
    logout successful
    (python3)$ anaconda -v login --username drf5n --password $JUNK
    login successful
    (python3)$ . activate py27
    discarding /Users/drf/anaconda/envs/python3/bin from PATH
    prepending /Users/drf/anaconda/envs/py27/bin to PATH
    (py27)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Anonymous User
    (py27)$ . activate python3
    discarding /Users/drf/anaconda/envs/py27/bin from PATH
    prepending /Users/drf/anaconda/envs/python3/bin to PATH
    (python3)$ anaconda whoami
    Using anaconda-server api site https://api.anaconda.org
    Username: drf5n
    Member since: Sat Jun 13 10:01:53 2015
      +user_type: user
    (python3)$

**Comment by drf5n** [comment]
That the work-around login in my python3 environments appears to login does not fix the initial problem I was having:

    (python3)$ conda install -c r r-irkernel
    Fetching package metadata: ....Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/t/<TOKEN>/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/dr-8c1f8f51-e318-4c8f-aac4-b02c7ea6f335/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/r/noarch/repodata.json.bz2)Warning: you may need to login to binstar again with 'binstar login' to access private packages(https://conda.anaconda.org/r/noarch/, 
    .....^C
    ... KeyboardInterrupt
    (python3)$ 
    (python3)$ conda --version
    conda 3.14.1

**Comment by dsludwig** [comment]
@drf5n 

The warning from `conda install` will happen if you have conda channels containing expired/revoked tokens. To debug this:

```
$ conda config --get channels
--add channels 'defaults'
--add channels 'https://conda.anaconda.org/t/TOKEN/username'
$ echo "TOKEN" > tmp-token
$ anaconda -t tmp-token auth -i
```

If the token is still valid, it will display:

```
Using anaconda-server api site https://api.anaconda.org
Name: binstar_client:user@machine
Id: 5641280d49c2384d401deb31
```

Otherwise it will show:

```
[Unauthorized] ('Invalid Token', 401)
```

The channel name containing the invalid token can be removed using:
```
conda config --remove channels http://conda.anaconda.org/t/TOKEN/username
```

You can then generate a new token and add it to your conda channels: 
http://docs.anaconda.org/using.html#Tokens

**Comment by srossross** [comment]
This is fixed in the latest release.

**Comment by drf5n** [comment]
@dsludwig -- I only had '--add-channels default' listed, with not other channels or tokens listed.

Latest release of what?  'conda update conda' didn't fix it.  A 'conda update anaconda'  appears to allow me to logout without asking for me to login again.  But even with an updated conda and anaconda, login doesn't appear to recognize that I'm logged in properly:

    $ 
    $ conda --version
    conda 3.18.9
    $ anaconda --version
    anaconda Command line client (version 1.2.1)
    $ python --version
    Python 2.7.11 :: Anaconda 2.4.1 (x86_64)
    $ anaconda logout
    Using Anaconda Cloud api site https://api.anaconda.org
    logout successful
    $ anaconda login
    Using Anaconda Cloud api site https://api.anaconda.org
    Username: drf5n
    drf5n's Password: 
    [WARNING] It appears you are already logged in from host v21837.local
    [WARNING] Logging in again will remove the previous token.  (This could cause troubles with virtual machines with the same hostname)
    [WARNING] Otherwise you can login again and specify a different hostname with "--hostname"
    Would you like to continue [Y|n]: y
    drf5n's login successful
    $ anaconda whoami
    Using Anaconda Cloud api site https://api.anaconda.org
    Anonymous User
    $ 

I also still get the same series of errors if I try 'conda install -c r r-irkernel'.  If I let the loop run for a while it eventually faults out with a "RuntimeError: maximum recursion depth exceeded in cmp".
