### ISSUE TITLE
anaconda remove errors from server.

### ISSUE THREAD

**Issue by flamingbear** [Anaconda-Server/anaconda-client#265]
Trying to work around my other issues: #264  & https://github.com/Anaconda-Server/support/issues/11 I thought I would just use anaconda remove before trying to upload a new package.  It appears to give me an error the first time I try and then succeed after that when using the --force flag each time.

Try to remove the linux version.
```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
[ServerError] ('Internal server error', 500)
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/linux-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
```

Try to remove the osx version:
```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
[ServerError] ('Internal server error', 500)
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2 --force
Using anaconda-server api site https://api.anaconda.org
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$
```

If I don't use the --force flag I get different errors:

```
vagrant@varcticice:/var/lib/jenkins/workspaces/seaicedata/ci/source$ anaconda -t $ANACONDA_TOKEN remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2
Using anaconda-server api site https://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/opt/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 82, in main
    description=__doc__, version=version)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
    return args.main(args)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/commands/remove.py", line 25, in main
    if args.force or bool_input(msg, False):
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/utils/__init__.py", line 323, in bool_input
    inpt = input('%s %s: ' % (prompt, default_str))
AttributeError: 'ColorStream' object has no attribute 'errors'
```

**Comment by PeterDSteinberg** [comment]
@flamingbear Could you post here the results of ```conda list``` here (listing of packages and version numbers), or at least the parts of that output that relate to ```anaconda-client```, ```anaconda-build```, ```clyent```, and/or ```binstar-server```.  I am wondering if at least the ```ColorStream``` error has already been fixed in newer versions.

**Comment by flamingbear** [comment]
Hi, I actually thought of that after I posted.  I conda updated everything I could think of.  Here's the current conda list.

And I "swear"(tm) that this was still broken, but now it appears to be functional.
I will look on another package and see if it is failing with older anaconda-client and report back...

```
vagrant@varcticice:~$ conda list
# packages in environment at /opt/miniconda:
#
anaconda-client           1.2.1                    py35_0    defaults
bumpversion               0.5.3                    py35_0    nsidc
clyent                    1.2.0                    py35_0    defaults
conda                     3.19.0                   py35_0    defaults
conda-build               1.18.2                   py35_0    defaults
conda-env                 2.4.5                    py35_0    defaults
freetype                  2.5.5                         0    defaults
invoke                    0.11.1                   py35_0    nsidc
jbig                      2.1                           0    defaults
jinja2                    2.8                      py35_0    defaults
jpeg                      8d                            0    defaults
libgfortran               1.0                           0    defaults
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         1    defaults
markupsafe                0.23                     py35_0    defaults
numpy                     1.10.1                   py35_0    defaults
openblas                  0.2.14                        3    defaults
openssl                   1.0.2d                        0    defaults
patchelf                  0.6                           0    defaults
pillow                    3.0.0                    py35_1    defaults
pip                       7.1.2                    py35_0    defaults
pycosat                   0.6.1                    py35_0    defaults
pycrypto                  2.6.1                    py35_0    defaults
python                    3.5.1                         0    defaults
python-dateutil           2.4.2                    py35_0    defaults
pytz                      2015.7                   py35_0    defaults
pyyaml                    3.11                     py35_1    defaults
readline                  6.2                           2    defaults
requests                  2.9.0                    py35_0    defaults
seaicedata                0.1.0dev                 py35_0    nsidc
setuptools                19.1.1                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
sqlite                    3.8.4.1                       1    defaults
tk                        8.5.18                        0    defaults
wheel                     0.26.0                   py35_1    defaults
xz                        5.0.5                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         0    defaults
```

**Comment by flamingbear** [comment]
So on another project I still get the remove error:

```
vagrant@vfreezingrink:~$ anaconda -t $token remove nsidc/seaicetimeseries/0.1.0dev/linux-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2
Using Anaconda Cloud api site https://api.anaconda.org
Are you sure you want to remove file nsidc/seaicetimeseries/0.1.0dev/linux-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2 ? [y|N]: y
[ServerError] ('Internal server error', 500)
vagrant@vfreezingrink:~$ conda list
# packages in environment at /opt/miniconda:
#
anaconda-client           1.2.1                    py35_0    defaults
bumpversion               0.5.3                    py35_0    nsidc
clyent                    1.2.0                    py35_0    defaults
conda                     3.19.0                   py35_0    defaults
conda-build               1.18.2                   py35_0    defaults
conda-env                 2.4.5                    py35_0    defaults
invoke                    0.11.1                   py35_0    nsidc
jinja2                    2.8                      py35_0    defaults
markupsafe                0.23                     py35_0    defaults
openssl                   1.0.2d                        0    defaults
patchelf                  0.6                           0    defaults
pip                       7.1.2                    py35_0    defaults
pycosat                   0.6.1                    py35_0    defaults
pycrypto                  2.6.1                    py35_0    defaults
python                    3.5.1                         0    defaults
python-dateutil           2.4.2                    py35_0    defaults
pytz                      2015.7                   py35_0    defaults
pyyaml                    3.11                     py35_1    defaults
readline                  6.2                           2    defaults
requests                  2.9.0                    py35_0    defaults
setuptools                19.1.1                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
sqlite                    3.8.4.1                       1    defaults
tk                        8.5.18                        0    defaults
wheel                     0.26.0                   py35_1    defaults
xz                        5.0.5                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         0    defaults
```

**Comment by flamingbear** [comment]
For what it's worth.  I can delete the other package from vfreezingrink.  Meaning removing seaicetimeseries is failing, and removing seaicedata is working.  Or it appears to be that way to me.

```
 Cloud api site https://api.anaconda.org
Are you sure you want to remove file nsidc/seaicetimeseries/0.1.0dev/osx-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2 ? [y|N]: y
[ServerError] ('Internal server error', 500)
vagrant@vfreezingrink:~$ anaconda -t $token remove nsidc/seaicedata/1.0.3dev/linux-64/seaicedata-1.0.3dev-py35_0.tar.bz2 Using Anaconda Cloud api site https://api.anaconda.org
Are you sure you want to remove file nsidc/seaicedata/1.0.3dev/linux-64/seaicedata-1.0.3dev-py35_0.tar.bz2 ? [y|N]: y
vagrant@vfreezingrink:~$ anaconda -t $token remove nsidc/seaicedata/1.0.3dev/osx-64/seaicedata-1.0.3dev-py35_0.tar.bz2 Using Anaconda Cloud api site https://api.anaconda.org
Are you sure you want to remove file nsidc/seaicedata/1.0.3dev/osx-64/seaicedata-1.0.3dev-py35_0.tar.bz2 ? [y|N]: y
vagrant@vfreezingrink:~$ echo $?
0
```

**Comment by PeterDSteinberg** [comment]
Could it be a bad token?  The usage of ```$token``` in the quote above is different from the above examples with ```$ANACONDA_TOKEN```.  Could it be, @flamingbear, that one token is okay and the other one is undefined or expired?

**Comment by flamingbear** [comment]
I will look, but I just got tired of typing ANACONDA_TOKEN on the commandline, so stored it in token.

No, they are identical tokens on both machines.

**Comment by PeterDSteinberg** [comment]
Okay. Thank you for checking.  Can you repeat one of the commands, @flamingbear, that is causing an error, but add the ```--show-traceback``` argument to ```anaconda``` so we can see more info about the 500 status error.  An example would be:
```
anaconda -t $ANACONDA_TOKEN --show-traceback remove nsidc/seaicedata/1.0.2dev/osx-64/seaicedata-1.0.2dev-py35_0.tar.bz2
```

**Comment by flamingbear** [comment]
Sure, but I have to do it with seaicetimeseries since seaicedata doesn't seem to be having the problem anymore...

```
vagrant@varcticice:~$ anaconda -t $token --show-traceback remove nsidc/seaicetimeseries/0.1.0dev/osx-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2
Using Anaconda Cloud api site https://api.anaconda.org
Are you sure you want to remove file nsidc/seaicetimeseries/0.1.0dev/osx-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2 ? [y|N]: y
[ERROR]
Traceback (most recent call last):
  File "/opt/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/commands/remove.py", line 26, in main
    aserver_api.remove_dist(spec.user, spec.package, spec.version, spec.basename)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 345, in remove_dist
    self._check_response(res)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 161, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal server error', 500)
```
Note that after the above command, and then just running again, it shows that the file was deleted from the server.

```
vagrant@varcticice:~$ anaconda -t $token --show-traceback remove nsidc/seaicetimeseries/0.1.0dev/osx-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2
Using Anaconda Cloud api site https://api.anaconda.org
Are you sure you want to remove file nsidc/seaicetimeseries/0.1.0dev/osx-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2 ? [y|N]: y
[ERROR]
Traceback (most recent call last):
  File "/opt/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/commands/remove.py", line 26, in main
    aserver_api.remove_dist(spec.user, spec.package, spec.version, spec.basename)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 345, in remove_dist
    self._check_response(res)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 161, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: (" distribution u'osx-64/seaicetimeseries-0.1.0dev-py35_0.tar.bz2' does not exist", 404)
vagrant@varcticice:~$
```

**Comment by PeterDSteinberg** [comment]
Good info.  Thanks.  I'll look into this further.

**Comment by flamingbear** [comment]
@PeterDSteinberg So here's some more information.
It looks like it might have something to do with particular versions of packages.  We also have a package sedna, which was unchanged for 8 days, and I kicked off our CI which tried to replace the existing package, it failed trying to remove the existing package:

```

Uploading file nsidc/sedna/1.0.0dev/linux-64/sedna-1.0.0dev-py35_0.tar.bz2 ... 
Using Anaconda Cloud api site https://api.anaconda.org
[WARNING] Distribution linux-64/sedna-1.0.0dev-py35_0.tar.bz2 already exists ... removing
[ERROR] 
Traceback (most recent call last):
  File "/opt/miniconda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 194, in main
    if remove_existing_file(aserver_api, args, username, package_name, version, file_attrs):
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 135, in remove_existing_file
    aserver_api.remove_dist(username, package_name, version, file_attrs['basename'])
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 345, in remove_dist
    self._check_response(res)
  File "/opt/miniconda/lib/python3.5/site-packages/binstar_client/__init__.py", line 161, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('Internal server error', 500)
```

But if I ignore the existing package and create a new version of the package:  `v1.0.1dev` CI is happy again and I don't get any errors when I try to replace the v1.0.1dev package.

```
Uploading file nsidc/sedna/1.0.1dev/linux-64/sedna-1.0.1dev-py35_0.tar.bz2 ... 
Using Anaconda Cloud api site https://api.anaconda.org
[WARNING] Distribution linux-64/sedna-1.0.1dev-py35_0.tar.bz2 already exists ... removing

 uploaded 0 of 34Kb: 0.00% ETA: 0.0 minutes
 uploaded 0 of 34Kb: 0.10% ETA: 5.8 minutes
 uploaded 0 of 34Kb: 0.24% ETA: 2.5 minutes
 uploaded 0 of 34Kb: 0.24% ETA: 2.5 minutes
 uploaded 0 of 34Kb: 1.69% ETA: 0.3 minutes
 uploaded 0 of 34Kb: 1.69% ETA: 0.3 minutes
 uploaded 0 of 34Kb: 1.80% ETA: 0.3 minutes
 uploaded 0 of 34Kb: 1.97% ETA: 0.3 minutes
 uploaded 0 of 34Kb: 1.98% ETA: 0.3 minutes
....
```

This behavior explains why my seaicedata package stopped exhibiting problems because I forced a release and bumped the version to a new dev package.

**Comment by srossross** [comment]
@rafaelhbarros should this be 'in-progress'?

**Comment by dsludwig** [comment]
@flamingbear do you still have this problem? I suspect this is fixed by the change for #264

**Comment by flamingbear** [comment]
I'm sorry I have actually killed off all of the packages that were exhibiting this behavior.  I am not experiencing this with any of my current package versions.  I also suspect #264 fixed this, so please close this and I'll open a new ticket if I see this again.  Thanks.  Matt
